import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shadcn-ui Dashoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-white text-black flex flex-col`,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
          <TooltipProvider>
            <div className="flex flex-1">
              {/* Sidebar */}
              <SideNavbar />

              {/* main page */}
              <div className="p-8 w-full">{children}</div>
            </div>
            <Footer />
          </TooltipProvider>
      </body>
    </html>
  );
}
